### ISSUE TITLE
Add more prompt selections

### ISSUE THREAD

**Issue by ajcwebdev** [ajcwebdev/autoshow#47]
## New Prompt Options

- `faq` - Create a list of frequently asked questions and their answers based on the transcript.
- `bulletPoints` - Create a bullet point list summarizing the transcript.
- Different summary lengths similar to different chapter description lengths:
  - `shortSummary` - One sentence.
  - `longSummary` - One paragraph.
- Generate songs:
  - `rapSong` - Create a rap song based on the transcript.
  - `rockSong` - Create a rock song based on the transcript.
  - `countrySong` - Create a country song based on the transcript.

<code>rapSong</code> prompt

```js
// Section for generating a rap song based on the transcript
rapSong: {
  // Instructions for creating the rap song
  instruction: `- Write a highly complex, multi-syllabic rhyming, Eminem inspired rap based on this transcript.
  - Do not rhyme any words with themselves.
  - Give it a basic song structure with verses, choruses, and a bridge but do not write those markings above each section.
  - Give the song three potential titles.\n`,
  // Example rap song
  example: `## Song
  
  Lyrics to the song.`
}
```

### Test Command

```bash
npm run as -- --file "content/audio.mp3" --prompt rapSong
```

## Improve Current Prompt Options

Add the following to <code>questions</code> prompt

- This is a transcript of a lesson.
- Include a list of 10 questions to check the listeners' comprehension of the material.
  - Ensure questions cover all major sections of the content.
  - Ensure the questions are correct, emphasize the right things, and aren't redundant.
  - Do not say things like "the instructor describes" or "according to the lesson," assume that all the questions relate to the lesson told by the instructor.
  - The first five questions should be beginner level questions and the last five should be expert level questions.

**Comment by jennjunod** [comment]
Command used to run all song types `npm run as -- --file "content/audio.mp3" --prompt countrySong rapSong rockSong`

Output using ChatGPT to create https://gist.github.com/jennjunod/6602568da780c84280f55f2ea5f1ec83
